version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: ./app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: ./app
    command: ["rq", "worker", "default", "-c", "settings"]
    depends_on:
      - redis

  dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "9181:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./htpasswd:/etc/nginx/htpasswd
    depends_on:
      - dashboard

volumes:
  redis_data:
